### ISSUE TITLE
AudioRecorder doesn't work with Asset Store version of the Recorder

### ISSUE THREAD

**Issue by gekidoslair** [Unity-Technologies/film-tv-toolbox#1]
![audiorecordererrors](https://user-images.githubusercontent.com/4552687/51794501-033bd600-2189-11e9-87cf-a41ee3af2b6e.jpg)

with the latest version of the Recorder (from the asset store), the Audio Recorder throws these errors

**Comment by jeromemaurey** [comment]
I've just tested the Audio Recorder with 1.0.2 of Recorder in a fresh 2018.3.6f1 project and didn't get these errors. Have you managed to fix the issue on your end? Otherwise, could you share which version of Unity you are using?

**Comment by mfe** [comment]
Closing this as question has been answered. You need to use the AudioRecorder.unitypackage, so the files can be inserted in the right location of Recorder.
