### ISSUE TITLE
Some of the code is deprecated in 2019.3 

### ISSUE THREAD

**Issue by williamf117** [Unity-Technologies/film-tv-toolbox#18]
importing into 2019.3 gives a long list of errors not sure if I am missing a dependency or if something just got deprecated.

![Capture](https://user-images.githubusercontent.com/25187152/74381004-eaa85900-4da7-11ea-9b63-01c0d897eb94.PNG)

**Comment by cguer** [comment]
Hey @williamf117, a few questions for you:
1. Are you downloading the package from the Unity Package Manager or pointing it to a local repository?
2. Do these errors appear in the Unity console right after installing the package?  If not, what exact steps are you taking before the errors are logged?

**Comment by williamf117** [comment]
I am pointing it to a local repo and the errors appear as soon as the package is loaded in the project.

**Comment by cguer** [comment]
Ahh my bad, I see you are trying to import the AudioRecorder package (I thought you were importing the whole Film TV Toolbox).  This AudioRecorder is now deprecated and only worked with an old version of the Recorder package (which was downloaded through the asset store.)

If you need to record audio you should instead install the [Recorder ](https://docs.unity3d.com/Packages/com.unity.recorder@2.1/manual/index.html)package from the Unity package manager.  The Recorder comes built-in with an option to record audio and is the currently maintained package.

Let me know if you still have the errors after!
