### ISSUE TITLE
AudioRecorder soesn't work with "Unity Recorder 2.0.0-preview.6" from package manager

### ISSUE THREAD

**Issue by rc1** [Unity-Technologies/film-tv-toolbox#9]
When using this with the package manager of Recorder (as advised on Recorder's asset store page) it does not work.

The error is due to Recorders classes being non-public.

The errors look the same as #1. 

A very nice features to have, I hope this can be fixed.

**Comment by mfe** [comment]
Hey !

We plan to integrate AudioRecorder to the main Recorder asap.

In the meantime, here's an how to force it into the 2.0.0 package : https://forum.unity.com/threads/unity-recorder-custom-bitrate.665239/#post-4465279

Sorry about that !

**Comment by mfe** [comment]
FYI AudioRecorder has been released in Recorder 2.0.1-preview.1 now available in Package Manager.
